name=premium-elearning
description=Premium E-Learning Theme
parent=keycloak
import=common/keycloak

# Account theme support
accountTheme=true
accountConsole=true

# Login theme
loginTheme=true

# Email theme
emailTheme=true
