server:
  port: 3002

spring:
  application:
    name: course-service
  datasource:
    url: jdbc:h2:tcp://h2-server:1522/coursedb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  h2:
    console:
      enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://host.docker.internal:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

# OpenFeign Client Configuration
openfeign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
