server:
  port: 3044

spring:
  application:
    name: feedback-service
  datasource:
    url: jdbc:mysql://mysql:3306/feedback_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: adminpassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://host.docker.internal:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
